#Lang.properties


login.text = Login

username.text = Enter Username

password.text = Enter Password

error.text = Error! Username or password is wrong!

no.upcoming.message = No upcoming appointments.

upcoming.message = Appointment coming up at:

late.message = Late to this appointment:

locale.text = Lang: EN

time.zone = Time Zone: 